name: ci

on:
  push:
  pull_request:

jobs:
  build-macos:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # IMPORTANT: drop any stale build artifacts (old generated_mem.cpp)
      - name: Clean build dir
        run: rm -rf build

      - name: Configure (CMake + Ninja)
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
