name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: ${{ matrix.os }} / CMake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Optional) make sure tools are present; runners usually have them already
      - name: Install build tools (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build

      - name: Install build tools (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake ninja || true

      - name: Configure (CMake)
        run: |
          cmake -S . -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build -- -j

      - name: Run ctests
        run: ctest --test-dir build --output-on-failure

      # Nice-to-have: upload build dir on failure for debugging
      - name: Upload build logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: build
