name: ci
on:
  push:
  pull_request:

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: |
          mkdir build && cd build
          cmake -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET=12.2 ..
      - name: Build app
        run: |
          cd build
          xcodebuild -project seedos.xcodeproj -scheme seedos -configuration Debug -destination 'platform=macOS' build
      - name: Build & run tests
        run: |
          cd build
          xcodebuild -project seedos.xcodeproj -scheme seedos_tests -configuration Debug -destination 'platform=macOS' build
          ./Debug/seedos_tests
