name: ci

on:
  push:
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: brew install ninja

      - name: Configure (CMake + Ninja)
        run: |
          cmake -S . -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0

      - name: Build
        run: cmake --build build --parallel

      - name: Smoke tests (don’t fail CI if absent)
        run: ctest --test-dir build --output-on-failure || true
